### ISSUE TITLE
Environment installation

### ISSUE THREAD

**Issue by Aghnar2010** [ydoherty/CoastSat.PlanetScope#11]
Hello,

I made several attempts to install the environment. yml and the environment_alt.yml, but in the first case the installation never stops and in the second I get errors.
Is it a problem with the environments ?
Otherwise, I'm thinking of trying coastsat.

Thanks

**Comment by ydoherty** [comment]
Hi Aghnar,

I’ve tested both environments on Mac and windows and have got them to work.
A few people have had trouble installing the environment but it’s hard for
me to debug if I can’t replicate the error myself. What operating system
are you using?

For the environment you say never stops, I would try leave it to run
overnight and see if that works. Conda can be incredibly slow on some
systems.

If that fails, an alternative would be to try installing the environment
using mamba instead of Conda. It works a lot faster at resolving package
conflicts so may work better. You can google something along the lines of
mamba package installer and it should get you there.

You can also use coastsat. It just depends on your application. Coastsat
uses 10/30m resolution pixels, whereas planet scope is 3m pixels. Coastsat
also sometimes has installation errors.

If none of the above work and coastsat works, you can also try run coastsat
planetscope from your coastsat environment. It will raise errors saying
certain packages are not installed, so when that arises just install each
new package into the coastsat environment.

Lastly you can have a look through closed issues on the GitHub page as some
of the discussions may be relevant or help you.

Let me know how you go and if you get it to work please let me know so I
can update the repo.

Cheers,
Yarran

**Comment by Aghnar2010** [comment]
Thank you for your reply.

I use Windows with anaconda to run the commands (CMDprompt). I'm going to try to leave it running all night.

I also use coastsat and have had no problems with it.

I'll keep you informed of my progress, thank you.

Florian.

**Comment by ydoherty** [comment]
Let me know how you go or if any of the other options work for you.

Cheers
Yarran
