### ISSUE TITLE
List index out of range - Scene merging

### ISSUE THREAD

**Issue by Jand607** [ydoherty/CoastSat.PlanetScope#21]
Hi, I've downloaded all of my PlanetScope imagery and am now trying to perform scene merging (step 1.3), which is the following command:
![image](https://github.com/user-attachments/assets/105251d5-3908-4afb-a399-e76da843d679)

Unfortunately, I am getting the following error:

![image](https://github.com/user-attachments/assets/891c722b-5586-4595-a3a7-5d3b78722389)

Note that the second time I run it, I get a different error: 

![image](https://github.com/user-attachments/assets/cdc8e964-1a33-4a50-b07b-7d06e3cdc43c)

The first image (25th January 2016) is fully preprocessed, but the second image (29th) only gets as far as the TOA and does not reach the NaN mask.

Thanks for your help,

Jack

**Comment by ydoherty** [comment]
Hi Jack, it looks like you're trying to process 1100 images on the first go. I'd strongly recommend you copy maybe 25-50 images into a new folder and run the toolkit on that smaller sample to debug any issues and get all the inputs dialled for your site. I'd also suggest if you've got a large AOI, that you make a smaller AOI for the first pass testing. You can still use the images you have downloaded already, the toolkit will clip them to the smaller AOI during processing. With a subset of images and a smaller AOI it will run way faster and make your life a lot easier. Once you have the process and settings figured out, I'd then run it on the full set of data and larger AOI. 

I've done a major overhaul of the useability side of the toolkit this week. The process for setting up the land mask (essential for good coregistration) is now visual so should be significantly easier to get working and debug. I strongly recommmend you download a fresh set of all the codes and start new! Running in spyder is also a lot easier to debug than running the jupyter notebooks. 

When the toolkit crashes on an individual image, sometimes it's because there are issues with that individual image or UDM mask. I'd import the raw file and data mask into QGIS to see if there are problems. If there are problems with the image, you can just delete all the files associated with it from the downloads folder so the toolkit doesnt use it. 

RE getting a different error message when running the same cell, I think I fixed that bug today. 

Sometimes when you're having issues, it can be worthwhile restarting the spyder/jupyter terminal and trying again from the start. You can also delete the folder 'planetscope_ps > outputs > SITE' for a completely fresh start. 

Hopefully that all helps. 

Cheers, 
Yarran
